# Generated by Django 4.0.4 on 2022-05-29 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquadsDataModel',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gameweek', models.CharField(blank=True, max_length=250, null=True)),
                ('nameSquad', models.CharField(blank=True, max_length=250, null=True)),
                ('element', models.CharField(blank=True, max_length=250, null=True)),
                ('totalPoints', models.IntegerField(blank=True, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('cleanSheets', models.IntegerField(blank=True, null=True)),
                ('goalsConceded', models.IntegerField(blank=True, null=True)),
                ('ownGoals', models.IntegerField(blank=True, null=True)),
                ('penaltiesSaved', models.IntegerField(blank=True, null=True)),
                ('penaltiesMissed', models.IntegerField(blank=True, null=True)),
                ('yellowCards', models.IntegerField(blank=True, null=True)),
                ('redCards', models.IntegerField(blank=True, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('bonus', models.IntegerField(blank=True, null=True)),
                ('bps', models.IntegerField(blank=True, null=True)),
                ('influence', models.FloatField(blank=True, null=True)),
                ('creativity', models.FloatField(blank=True, null=True)),
                ('threat', models.FloatField(blank=True, null=True)),
                ('ict_index', models.FloatField(blank=True, null=True)),
                ('values', models.IntegerField(blank=True, null=True)),
                ('selected', models.IntegerField(blank=True, null=True)),
                ('transfersIn', models.IntegerField(blank=True, null=True)),
                ('transfersOut', models.IntegerField(blank=True, null=True)),
                ('captain', models.BooleanField(default=False)),
                ('viceCaptain', models.BooleanField(default=False)),
                ('multiplier', models.IntegerField(blank=True, null=True)),
                ('entryName', models.CharField(blank=True, max_length=250, null=True)),
                ('eventTotal', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('twentyTenName', models.CharField(blank=True, max_length=250, null=True)),
                ('entry', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
